server:
  port: 8081

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    mail:
      enabled: false

logging:
  level:
    root: INFO
    web: INFO

# JWT Configuration
jwt:
  secret: mySecretKey1234567890123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# OpenAPI Configuration
openapi:
  service:
    title: Access Control List API
    version: 1.0.0
    api-docs: backend-service
    server: http://localhost:8081




